---
# yamllint disable rule:line-length
name: Pull Request
on:
  pull_request:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          token: ${{ github.token }}
          fetch-depth: "0"
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.3.0
          tf_actions_subcommand: init
          tf_actions_working_dir: example/examplea
      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.3.0
          tf_actions_subcommand: validate
          tf_actions_working_dir: example/examplea
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          token: ${{ github.token }}
          fetch-depth: "0"
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.9
      - uses: pre-commit/action@v3.0.0
